name: Aggiorna Notizie

on:
  schedule:
    - cron: "0 */6 * * *" # Esegui ogni 6 ore
  workflow_dispatch: # Permette di eseguire manualmente

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios cheerio dotenv

      - name: Esegui lo script di scraping
        run: node scraper.js

      - name: Commit & Push se ci sono modifiche
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/notizie.json
          git commit -m "Aggiornate le notizie" || echo "Nessuna modifica"
          git push
